// Local, hand-authored SVG assets. Species anchors share the same 320×320 canvas.
export const creatureAssets = Object.freeze({
  bloomhart: Object.freeze({ front: '/assets/creatures/bloomhart-front.svg', back: '/assets/creatures/bloomhart-back.svg' }),
  breezefinch: Object.freeze({ front: '/assets/creatures/breezefinch-front.svg', back: '/assets/creatures/breezefinch-back.svg' }),
  brightkit: Object.freeze({ front: '/assets/creatures/brightkit-front.svg', back: '/assets/creatures/brightkit-back.svg' }),
  clovermink: Object.freeze({ front: '/assets/creatures/clovermink-front.svg', back: '/assets/creatures/clovermink-back.svg' }),
  dawnmonarch: Object.freeze({ front: '/assets/creatures/dawnmonarch-front.svg', back: '/assets/creatures/dawnmonarch-back.svg' }),
  dawnstag: Object.freeze({ front: '/assets/creatures/dawnstag-front.svg', back: '/assets/creatures/dawnstag-back.svg' }),
  dewbud: Object.freeze({ front: '/assets/creatures/dewbud-front.svg', back: '/assets/creatures/dewbud-back.svg' }),
  meadowram: Object.freeze({ front: '/assets/creatures/meadowram-front.svg', back: '/assets/creatures/meadowram-back.svg' }),
  puffkip: Object.freeze({ front: '/assets/creatures/puffkip-front.svg', back: '/assets/creatures/puffkip-back.svg' }),
  reedhopper: Object.freeze({ front: '/assets/creatures/reedhopper-front.svg', back: '/assets/creatures/reedhopper-back.svg' }),
  sprigcalf: Object.freeze({ front: '/assets/creatures/sprigcalf-front.svg', back: '/assets/creatures/sprigcalf-back.svg' }),
  sunbead: Object.freeze({ front: '/assets/creatures/sunbead-front.svg', back: '/assets/creatures/sunbead-back.svg' }),
  barkbeetle: Object.freeze({ front: '/assets/creatures/barkbeetle-front.svg', back: '/assets/creatures/barkbeetle-back.svg' }),
  barkling: Object.freeze({ front: '/assets/creatures/barkling-front.svg', back: '/assets/creatures/barkling-back.svg' }),
  canopylord: Object.freeze({ front: '/assets/creatures/canopylord-front.svg', back: '/assets/creatures/canopylord-back.svg' }),
  eldercanopy: Object.freeze({ front: '/assets/creatures/eldercanopy-front.svg', back: '/assets/creatures/eldercanopy-back.svg' }),
  fernpup: Object.freeze({ front: '/assets/creatures/fernpup-front.svg', back: '/assets/creatures/fernpup-back.svg' }),
  gladefox: Object.freeze({ front: '/assets/creatures/gladefox-front.svg', back: '/assets/creatures/gladefox-back.svg' }),
  hollowlynx: Object.freeze({ front: '/assets/creatures/hollowlynx-front.svg', back: '/assets/creatures/hollowlynx-back.svg' }),
  mossbell: Object.freeze({ front: '/assets/creatures/mossbell-front.svg', back: '/assets/creatures/mossbell-back.svg' }),
  owlmoss: Object.freeze({ front: '/assets/creatures/owlmoss-front.svg', back: '/assets/creatures/owlmoss-back.svg' }),
  sapwing: Object.freeze({ front: '/assets/creatures/sapwing-front.svg', back: '/assets/creatures/sapwing-back.svg' }),
  shadefern: Object.freeze({ front: '/assets/creatures/shadefern-front.svg', back: '/assets/creatures/shadefern-back.svg' }),
  twigveil: Object.freeze({ front: '/assets/creatures/twigveil-front.svg', back: '/assets/creatures/twigveil-back.svg' }),
  arcbadger: Object.freeze({ front: '/assets/creatures/arcbadger-front.svg', back: '/assets/creatures/arcbadger-back.svg' }),
  bedrocktitan: Object.freeze({ front: '/assets/creatures/bedrocktitan-front.svg', back: '/assets/creatures/bedrocktitan-back.svg' }),
  coalcub: Object.freeze({ front: '/assets/creatures/coalcub-front.svg', back: '/assets/creatures/coalcub-back.svg' }),
  coppercoil: Object.freeze({ front: '/assets/creatures/coppercoil-front.svg', back: '/assets/creatures/coppercoil-back.svg' }),
  dustwraith: Object.freeze({ front: '/assets/creatures/dustwraith-front.svg', back: '/assets/creatures/dustwraith-back.svg' }),
  flintvole: Object.freeze({ front: '/assets/creatures/flintvole-front.svg', back: '/assets/creatures/flintvole-back.svg' }),
  geodewyrm: Object.freeze({ front: '/assets/creatures/geodewyrm-front.svg', back: '/assets/creatures/geodewyrm-back.svg' }),
  gritmole: Object.freeze({ front: '/assets/creatures/gritmole-front.svg', back: '/assets/creatures/gritmole-back.svg' }),
  ironshell: Object.freeze({ front: '/assets/creatures/ironshell-front.svg', back: '/assets/creatures/ironshell-back.svg' }),
  loamhorn: Object.freeze({ front: '/assets/creatures/loamhorn-front.svg', back: '/assets/creatures/loamhorn-back.svg' }),
  pebblenib: Object.freeze({ front: '/assets/creatures/pebblenib-front.svg', back: '/assets/creatures/pebblenib-back.svg' }),
  tunnelrat: Object.freeze({ front: '/assets/creatures/tunnelrat-front.svg', back: '/assets/creatures/tunnelrat-back.svg' }),
  duneear: Object.freeze({ front: '/assets/creatures/duneear-front.svg', back: '/assets/creatures/duneear-back.svg' }),
  duneharrier: Object.freeze({ front: '/assets/creatures/duneharrier-front.svg', back: '/assets/creatures/duneharrier-back.svg' }),
  dustmite: Object.freeze({ front: '/assets/creatures/dustmite-front.svg', back: '/assets/creatures/dustmite-back.svg' }),
  glasstail: Object.freeze({ front: '/assets/creatures/glasstail-front.svg', back: '/assets/creatures/glasstail-back.svg' }),
  gritfinch: Object.freeze({ front: '/assets/creatures/gritfinch-front.svg', back: '/assets/creatures/gritfinch-back.svg' }),
  miragecat: Object.freeze({ front: '/assets/creatures/miragecat-front.svg', back: '/assets/creatures/miragecat-back.svg' }),
  mirrormoth: Object.freeze({ front: '/assets/creatures/mirrormoth-front.svg', back: '/assets/creatures/mirrormoth-back.svg' }),
  sandhop: Object.freeze({ front: '/assets/creatures/sandhop-front.svg', back: '/assets/creatures/sandhop-back.svg' }),
  sandwyrm: Object.freeze({ front: '/assets/creatures/sandwyrm-front.svg', back: '/assets/creatures/sandwyrm-back.svg' }),
  siroccopup: Object.freeze({ front: '/assets/creatures/siroccopup-front.svg', back: '/assets/creatures/siroccopup-back.svg' }),
  sunmonolith: Object.freeze({ front: '/assets/creatures/sunmonolith-front.svg', back: '/assets/creatures/sunmonolith-back.svg' }),
  sunscarab: Object.freeze({ front: '/assets/creatures/sunscarab-front.svg', back: '/assets/creatures/sunscarab-back.svg' }),
  abyssking: Object.freeze({ front: '/assets/creatures/abyssking-front.svg', back: '/assets/creatures/abyssking-back.svg' }),
  brinepup: Object.freeze({ front: '/assets/creatures/brinepup-front.svg', back: '/assets/creatures/brinepup-back.svg' }),
  deepglow: Object.freeze({ front: '/assets/creatures/deepglow-front.svg', back: '/assets/creatures/deepglow-back.svg' }),
  floefin: Object.freeze({ front: '/assets/creatures/floefin-front.svg', back: '/assets/creatures/floefin-back.svg' }),
  kelpcrab: Object.freeze({ front: '/assets/creatures/kelpcrab-front.svg', back: '/assets/creatures/kelpcrab-back.svg' }),
  lagoonmaw: Object.freeze({ front: '/assets/creatures/lagoonmaw-front.svg', back: '/assets/creatures/lagoonmaw-back.svg' }),
  pearlfry: Object.freeze({ front: '/assets/creatures/pearlfry-front.svg', back: '/assets/creatures/pearlfry-back.svg' }),
  reefpip: Object.freeze({ front: '/assets/creatures/reefpip-front.svg', back: '/assets/creatures/reefpip-back.svg' }),
  shellwisp: Object.freeze({ front: '/assets/creatures/shellwisp-front.svg', back: '/assets/creatures/shellwisp-back.svg' }),
  tidalray: Object.freeze({ front: '/assets/creatures/tidalray-front.svg', back: '/assets/creatures/tidalray-back.svg' }),
  tideknot: Object.freeze({ front: '/assets/creatures/tideknot-front.svg', back: '/assets/creatures/tideknot-back.svg' }),
  tidesovereign: Object.freeze({ front: '/assets/creatures/tidesovereign-front.svg', back: '/assets/creatures/tidesovereign-back.svg' }),
  auroradrake: Object.freeze({ front: '/assets/creatures/auroradrake-front.svg', back: '/assets/creatures/auroradrake-back.svg' }),
  driftelk: Object.freeze({ front: '/assets/creatures/driftelk-front.svg', back: '/assets/creatures/driftelk-back.svg' }),
  frostchime: Object.freeze({ front: '/assets/creatures/frostchime-front.svg', back: '/assets/creatures/frostchime-back.svg' }),
  frostpaw: Object.freeze({ front: '/assets/creatures/frostpaw-front.svg', back: '/assets/creatures/frostpaw-back.svg' }),
  glacierfin: Object.freeze({ front: '/assets/creatures/glacierfin-front.svg', back: '/assets/creatures/glacierfin-back.svg' }),
  glaciersaint: Object.freeze({ front: '/assets/creatures/glaciersaint-front.svg', back: '/assets/creatures/glaciersaint-back.svg' }),
  icemole: Object.freeze({ front: '/assets/creatures/icemole-front.svg', back: '/assets/creatures/icemole-back.svg' }),
  meltwater: Object.freeze({ front: '/assets/creatures/meltwater-front.svg', back: '/assets/creatures/meltwater-back.svg' }),
  rimekit: Object.freeze({ front: '/assets/creatures/rimekit-front.svg', back: '/assets/creatures/rimekit-back.svg' }),
  sleetcrow: Object.freeze({ front: '/assets/creatures/sleetcrow-front.svg', back: '/assets/creatures/sleetcrow-back.svg' }),
  snowhare: Object.freeze({ front: '/assets/creatures/snowhare-front.svg', back: '/assets/creatures/snowhare-back.svg' }),
  snowspool: Object.freeze({ front: '/assets/creatures/snowspool-front.svg', back: '/assets/creatures/snowspool-back.svg' }),
  basaltpup: Object.freeze({ front: '/assets/creatures/basaltpup-front.svg', back: '/assets/creatures/basaltpup-back.svg' }),
  cinderbug: Object.freeze({ front: '/assets/creatures/cinderbug-front.svg', back: '/assets/creatures/cinderbug-back.svg' }),
  cindermare: Object.freeze({ front: '/assets/creatures/cindermare-front.svg', back: '/assets/creatures/cindermare-back.svg' }),
  cinderwraith: Object.freeze({ front: '/assets/creatures/cinderwraith-front.svg', back: '/assets/creatures/cinderwraith-back.svg' }),
  fulgurmoth: Object.freeze({ front: '/assets/creatures/fulgurmoth-front.svg', back: '/assets/creatures/fulgurmoth-back.svg' }),
  indigospark: Object.freeze({ front: '/assets/creatures/indigospark-front.svg', back: '/assets/creatures/indigospark-back.svg' }),
  magmapup: Object.freeze({ front: '/assets/creatures/magmapup-front.svg', back: '/assets/creatures/magmapup-back.svg' }),
  obsidianwing: Object.freeze({ front: '/assets/creatures/obsidianwing-front.svg', back: '/assets/creatures/obsidianwing-back.svg' }),
  slagmite: Object.freeze({ front: '/assets/creatures/slagmite-front.svg', back: '/assets/creatures/slagmite-back.svg' }),
  sootcub: Object.freeze({ front: '/assets/creatures/sootcub-front.svg', back: '/assets/creatures/sootcub-back.svg' }),
  stormforge: Object.freeze({ front: '/assets/creatures/stormforge-front.svg', back: '/assets/creatures/stormforge-back.svg' }),
  tuffcrab: Object.freeze({ front: '/assets/creatures/tuffcrab-front.svg', back: '/assets/creatures/tuffcrab-back.svg' }),
  ashcrown: Object.freeze({ front: '/assets/creatures/ashcrown-front.svg', back: '/assets/creatures/ashcrown-back.svg' }),
  ashmoth: Object.freeze({ front: '/assets/creatures/ashmoth-front.svg', back: '/assets/creatures/ashmoth-back.svg' }),
  charhound: Object.freeze({ front: '/assets/creatures/charhound-front.svg', back: '/assets/creatures/charhound-back.svg' }),
  cindershrew: Object.freeze({ front: '/assets/creatures/cindershrew-front.svg', back: '/assets/creatures/cindershrew-back.svg' }),
  emberpod: Object.freeze({ front: '/assets/creatures/emberpod-front.svg', back: '/assets/creatures/emberpod-back.svg' }),
  flarewisp: Object.freeze({ front: '/assets/creatures/flarewisp-front.svg', back: '/assets/creatures/flarewisp-back.svg' }),
  infernarch: Object.freeze({ front: '/assets/creatures/infernarch-front.svg', back: '/assets/creatures/infernarch-back.svg' }),
  phoenixvale: Object.freeze({ front: '/assets/creatures/phoenixvale-front.svg', back: '/assets/creatures/phoenixvale-back.svg' }),
  pyrebull: Object.freeze({ front: '/assets/creatures/pyrebull-front.svg', back: '/assets/creatures/pyrebull-back.svg' }),
  pyrewraith: Object.freeze({ front: '/assets/creatures/pyrewraith-front.svg', back: '/assets/creatures/pyrewraith-back.svg' }),
  sparkmoth: Object.freeze({ front: '/assets/creatures/sparkmoth-front.svg', back: '/assets/creatures/sparkmoth-back.svg' }),
  voltfly: Object.freeze({ front: '/assets/creatures/voltfly-front.svg', back: '/assets/creatures/voltfly-back.svg' }),
});

export const eggAssets = Object.freeze({
  meadow: '/assets/eggs/meadow.svg',
  forest: '/assets/eggs/forest.svg',
  earth: '/assets/eggs/earth.svg',
  desert: '/assets/eggs/desert.svg',
  sea: '/assets/eggs/sea.svg',
  ice: '/assets/eggs/ice.svg',
  volcanic: '/assets/eggs/volcanic.svg',
  flame: '/assets/eggs/flame.svg',
});

export const itemAssets = Object.freeze({
  dew_leaf: '/assets/items/dew_leaf.svg',
  soft_seed: '/assets/items/soft_seed.svg',
  amber_drop: '/assets/items/amber_drop.svg',
  moss_thread: '/assets/items/moss_thread.svg',
  echo_bark: '/assets/items/echo_bark.svg',
  moon_spore: '/assets/items/moon_spore.svg',
  clay_shard: '/assets/items/clay_shard.svg',
  copper_flake: '/assets/items/copper_flake.svg',
  earth_heart: '/assets/items/earth_heart.svg',
  fine_sand: '/assets/items/fine_sand.svg',
  sun_salt: '/assets/items/sun_salt.svg',
  mirage_glass: '/assets/items/mirage_glass.svg',
  shell_chip: '/assets/items/shell_chip.svg',
  tide_kelp: '/assets/items/tide_kelp.svg',
  pearl_dust: '/assets/items/pearl_dust.svg',
  snow_crystal: '/assets/items/snow_crystal.svg',
  frost_moss: '/assets/items/frost_moss.svg',
  ancient_ice: '/assets/items/ancient_ice.svg',
  basalt_chip: '/assets/items/basalt_chip.svg',
  cobalt_shard: '/assets/items/cobalt_shard.svg',
  storm_ore: '/assets/items/storm_ore.svg',
  ash_petal: '/assets/items/ash_petal.svg',
  ember_seed: '/assets/items/ember_seed.svg',
  living_coal: '/assets/items/living_coal.svg',
  heat_herb: '/assets/items/heat_herb.svg',
  salve: '/assets/items/salve.svg',
  seal: '/assets/items/seal.svg',
  egg_feed: '/assets/items/egg_feed.svg',
  forest_balm: '/assets/items/forest_balm.svg',
  tide_balm: '/assets/items/tide_balm.svg',
  waking_salt: '/assets/items/waking_salt.svg',
  ember_incense: '/assets/items/ember_incense.svg',
  resonant_balm: '/assets/items/resonant_balm.svg',
  field_salve: '/assets/items/field_salve.svg',
  seal_fine: '/assets/items/seal_fine.svg',
  seal_true: '/assets/items/seal_true.svg',
  night_dew: '/assets/items/night_dew.svg',
  owl_fern: '/assets/items/owl_fern.svg',
  deep_ore: '/assets/items/deep_ore.svg',
  moon_glass: '/assets/items/moon_glass.svg',
  abyss_pearl: '/assets/items/abyss_pearl.svg',
  blue_vein: '/assets/items/blue_vein.svg',
  night_basalt: '/assets/items/night_basalt.svg',
  ash_ember: '/assets/items/ash_ember.svg',
  stone_pick: '/assets/items/stone_pick.svg',
  lantern: '/assets/items/lantern.svg',
  trowel: '/assets/items/trowel.svg',
  lens: '/assets/items/lens.svg',
  training_tonic: '/assets/items/training_tonic.svg',
  master_tonic: '/assets/items/master_tonic.svg',
  waking_draught: '/assets/items/waking_draught.svg',
  field_tonic: '/assets/items/field_tonic.svg',
  oak_log: '/assets/items/oak_log.svg',
  amber_log: '/assets/items/amber_log.svg',
  ghost_log: '/assets/items/ghost_log.svg',
  ember_log: '/assets/items/ember_log.svg',
  frost_log: '/assets/items/frost_log.svg',
  dawn_opal: '/assets/items/dawn_opal.svg',
  leaf_jade: '/assets/items/leaf_jade.svg',
  iron_garnet: '/assets/items/iron_garnet.svg',
  sun_topaz: '/assets/items/sun_topaz.svg',
  tide_sapphire: '/assets/items/tide_sapphire.svg',
  frost_beryl: '/assets/items/frost_beryl.svg',
  magma_ruby: '/assets/items/magma_ruby.svg',
  ember_diamond: '/assets/items/ember_diamond.svg',
  leaf_scale: '/assets/items/leaf_scale.svg',
  fin_shard: '/assets/items/fin_shard.svg',
  ember_fang: '/assets/items/ember_fang.svg',
  frost_claw: '/assets/items/frost_claw.svg',
  stone_horn: '/assets/items/stone_horn.svg',
  shade_fur: '/assets/items/shade_fur.svg',
  wind_feather: '/assets/items/wind_feather.svg',
  light_eye: '/assets/items/light_eye.svg',
  spark_vein: '/assets/items/spark_vein.svg',
  essence_grass: '/assets/items/essence_grass.svg',
  essence_water: '/assets/items/essence_water.svg',
  essence_ember: '/assets/items/essence_ember.svg',
  essence_ice: '/assets/items/essence_ice.svg',
  essence_stone: '/assets/items/essence_stone.svg',
  essence_shade: '/assets/items/essence_shade.svg',
  essence_wind: '/assets/items/essence_wind.svg',
  essence_light: '/assets/items/essence_light.svg',
  essence_spark: '/assets/items/essence_spark.svg',
  clover_bloom: '/assets/items/clover_bloom.svg',
  pine_resin: '/assets/items/pine_resin.svg',
  slate_dust: '/assets/items/slate_dust.svg',
  cactus_pulp: '/assets/items/cactus_pulp.svg',
  coral_bud: '/assets/items/coral_bud.svg',
  rime_salt: '/assets/items/rime_salt.svg',
  sulfur_clot: '/assets/items/sulfur_clot.svg',
  char_bloom: '/assets/items/char_bloom.svg',
  graft_starfall: '/assets/items/graft_starfall.svg',
  graft_cyclone: '/assets/items/graft_cyclone.svg',
  graft_sunburst: '/assets/items/graft_sunburst.svg',
  graft_glacier_break: '/assets/items/graft_glacier_break.svg',
  graft_boulder_slam: '/assets/items/graft_boulder_slam.svg',
  graft_arc_bolt: '/assets/items/graft_arc_bolt.svg',
  graft_rootquake: '/assets/items/graft_rootquake.svg',
  graft_night_veil: '/assets/items/graft_night_veil.svg',
  swift_tonic: '/assets/items/swift_tonic.svg',
  gale_tonic: '/assets/items/gale_tonic.svg',
  feast_stew: '/assets/items/feast_stew.svg',
  ward_balm: '/assets/items/ward_balm.svg',
  bond_charm: '/assets/items/bond_charm.svg',
  dawn_tonic: '/assets/items/dawn_tonic.svg',
  soothe_dust: '/assets/items/soothe_dust.svg',
  deep_lantern: '/assets/items/deep_lantern.svg',
  climb_rope: '/assets/items/climb_rope.svg',
  sea_mask: '/assets/items/sea_mask.svg',
  mole_claw: '/assets/items/mole_claw.svg',
  moon_oil: '/assets/items/moon_oil.svg',
  ember_wax: '/assets/items/ember_wax.svg',
  ironroot_log: '/assets/items/ironroot_log.svg',
  dunepalm_log: '/assets/items/dunepalm_log.svg',
  coral_log: '/assets/items/coral_log.svg',
  ash_log: '/assets/items/ash_log.svg',
  dew_extract: '/assets/items/dew_extract.svg',
  meadow_fiber: '/assets/items/meadow_fiber.svg',
  ghost_plank: '/assets/items/ghost_plank.svg',
  oak_plank: '/assets/items/oak_plank.svg',
  iron_ingot: '/assets/items/iron_ingot.svg',
  ironroot_plank: '/assets/items/ironroot_plank.svg',
  glass_pane: '/assets/items/glass_pane.svg',
  dunepalm_plank: '/assets/items/dunepalm_plank.svg',
  salt_brick: '/assets/items/salt_brick.svg',
  coral_plank: '/assets/items/coral_plank.svg',
  frost_plank: '/assets/items/frost_plank.svg',
  blue_ingot: '/assets/items/blue_ingot.svg',
  basalt_brick: '/assets/items/basalt_brick.svg',
  cobalt_ingot: '/assets/items/cobalt_ingot.svg',
  ash_plank: '/assets/items/ash_plank.svg',
  ember_alloy: '/assets/items/ember_alloy.svg',
  light_core: '/assets/items/light_core.svg',
  woven_band: '/assets/items/woven_band.svg',
  resonant_haft: '/assets/items/resonant_haft.svg',
  oak_frame: '/assets/items/oak_frame.svg',
  metal_frame: '/assets/items/metal_frame.svg',
  stone_core: '/assets/items/stone_core.svg',
  lens_blank: '/assets/items/lens_blank.svg',
  wind_vane: '/assets/items/wind_vane.svg',
  tide_core: '/assets/items/tide_core.svg',
  reef_haft: '/assets/items/reef_haft.svg',
  frost_frame: '/assets/items/frost_frame.svg',
  ice_core: '/assets/items/ice_core.svg',
  basalt_frame: '/assets/items/basalt_frame.svg',
  spark_core: '/assets/items/spark_core.svg',
  ash_haft: '/assets/items/ash_haft.svg',
  ember_core: '/assets/items/ember_core.svg',
  seal_master: '/assets/items/seal_master.svg',
  grand_salve: '/assets/items/grand_salve.svg',
  master_revive: '/assets/items/master_revive.svg',
  ember_charm: '/assets/items/ember_charm.svg',
  wind_charm: '/assets/items/wind_charm.svg',
  sage_tonic: '/assets/items/sage_tonic.svg',
  titan_tonic: '/assets/items/titan_tonic.svg',
  warding_balm: '/assets/items/warding_balm.svg',
  hearth_kit: '/assets/items/hearth_kit.svg',
  seed_cache: '/assets/items/seed_cache.svg',
  graft_tempest: '/assets/items/graft_tempest.svg',
  graft_worldbreak: '/assets/items/graft_worldbreak.svg',
  graft_solar_flare: '/assets/items/graft_solar_flare.svg',
  graft_absolute_zero: '/assets/items/graft_absolute_zero.svg',
  graft_void_maw: '/assets/items/graft_void_maw.svg',
  graft_leviathan: '/assets/items/graft_leviathan.svg',
});

export const assetLayout = Object.freeze({
  creature: Object.freeze({ width: 320, height: 320, anchorX: 160, anchorY: 264 }),
  egg: Object.freeze({ width: 128, height: 128, anchorX: 64, anchorY: 112 }),
  item: Object.freeze({ width: 64, height: 64, anchorX: 32, anchorY: 58 }),
});
